add_rules("mode.debug", "mode.release")
set_config("mode", "debug")
set_config("arch", "x64")

add_requires("emhash","thread-pool")

target("LNS")
    set_kind("binary")
    set_toolchains("msvc")
    set_languages("cxx20")
    add_cxflags("/utf-8")
    add_files("optimizer/lns/lns.cpp")
    set_rundir("$(projectdir)/")
    add_packages("emhash")

target("test_SA")
    set_kind("binary")
    set_toolchains("msvc")
    set_languages("cxx20")
    add_cxflags("/utf-8")
    add_files("optimizer/test_sa.cpp")
    set_rundir("$(projectdir)/")
    add_packages("emhash")

target("test_BNB")
    set_kind("binary")
    set_toolchains("msvc")
    set_languages("cxx20")
    add_cxflags("/utf-8")
    add_files("optimizer/test_bnb.cpp")
    set_rundir("$(projectdir)/")
    add_packages("emhash")

target("test_TABU")
    set_kind("binary")
    set_toolchains("msvc")
    set_languages("cxx20")
    add_cxflags("/utf-8")
    add_files("optimizer/test_tabu.cpp")
    set_rundir("$(projectdir)/")
    add_packages("emhash")

target("test_MEM")
    set_kind("binary")
    set_toolchains("msvc")
    set_languages("cxx20")
    add_cxflags("/utf-8")
    -- add_cxflags("/fsanitize=address", {tools = "msvc"})
    -- add_ldflags("/fsanitize=address", {tools = "msvc"})
    add_files("optimizer/test_mem.cpp")
    set_rundir("$(projectdir)/")
    add_packages("emhash","thread-pool")